.TH CG-TOOLS 7 CG-TOOLS
.SH NAME
cg-tools - Cooperative gamma tools
.SH DESCRIPTION
.B cg-tools
is a collection of utilities that change the colour output on monitors
without overriding each other.
.SH UTILITIES
.TP
.BR cg-brilliance (1)
Set the brilliance on the monitors.
.TP
.BR cg-darkroom (1)
Invert colour on the monitors and make them dark red.
.TP
.BR cg-gamma (1)
Adjust the gamma curves on the monitors.
.TP
.BR cg-icc (1)
Apply ICC profiles to the monitors.
.TP
.BR cg-limits (1)
Adjust the brightness and contrast on the monitors.
.TP
.BR cg-linear (1)
Create a span of priorities where adjustments are made
on unencoded (linear) RGB rather than encoded RGB.
.TP
.BR cg-negative (1)
Invert colour on the monitors.
.TP
.BR cg-query (1)
List output filters applied to a monitor.
.TP
.BR cg-rainbow (1)
Adds a rainbow cycle effect to the monitors.
.TP
.BR cg-remove (1)
Remove output filter from monitors.
.TP
.BR cg-sleepmode (1)
Gradually fade out the monitors, and gradually fade in on exit.
.SH "SEE ALSO"
.BR libcoopgamma (7),
.BR coopgammad (1)
.SH BUGS
Please report bugs to https://github.com/maandree/cg-tools/issues
or to maandree@kth.se
