PREFIX    = /usr
MANPREFIX = $(PREFIX)/share/man

PKGNAME = cg-tools

CC = c99

CPPFLAGS = -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D'PKGNAME="$(PKGNAME)"'
CFLAGS   = -O2
LDFLAGS  = -lcoopgamma -lm
